mkdir build
cd build

cmake \
  -G Ninja \
  -DCMAKE_INSTALL_PREFIX=$PREFIX \
  -DCMAKE_PREFIX_PATH=$PREFIX \
  -DLLDB_ENABLE_PYTHON=ON \
  -DLLDB_ENABLE_LIBEDIT=ON \
  -DLLDB_ENABLE_CURSES=ON \
  -DLLDB_ENABLE_LIBXML2=ON \
  -DLLDB_ENABLE_LIBXML2=ON \
  -DLLDB_ENABLE_TESTS=OFF \
  -DLLDB_USE_SYSTEM_DEBUGSERVER=ON \
  ..

ninja -j${CPU_COUNT}
ninja install
