# Requires 10.12 for os/log.h
# Requires 10.13 for SecuritySessionId
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.13"                # [osx and x86_64]
c_compiler:         # [osx and arm64]
  - clang_bootstrap # [osx and arm64]
cxx_compiler:       # [osx and arm64]
  - clang_bootstrap # [osx and arm64]
cudnn:                                            # [linux64]
  - undefined                                     # [linux64]
cuda_compiler_version:                            # [linux64]
  - None                                          # [linux64]
docker_image:                                     # [linux64]
  - quay.io/condaforge/linux-anvil-cos7-x86_64    # [linux64]
cdt_name:                                         # [linux64]
  - cos7                                          # [linux64]
