# Requires 10.12 for os/log.h
# Requires 10.13 for SecuritySessionId
# Requires 11.0 for ___isplatformversionatleast
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "11.0"                 # [osx and x86_64]
c_compiler:         # [osx and arm64]
  - clang_bootstrap # [osx and arm64]
cxx_compiler:       # [osx and arm64]
  - clang_bootstrap # [osx and arm64]
