{% set version = "7.0.0" %}
{% set sha256 = "7ff6d8fee49977d25b3b69be7d22937b92592c7609cf283ed0dcf9e5cd80aa32" %}

package:
  name: lldb
  version: {{ version }}

source:
  url: http://releases.llvm.org/{{ version }}/lldb-{{ version }}.src.tar.xz
  sha256: {{ sha256 }}
  patches:
    # Remove use of private header in LLDB
    # ref: https://reviews.llvm.org/D41824
    - D41824.patch

build:
  number: 0
  skip: true  # [win and py<35]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.4.3
    - ninja    # [win]
  host:
    - python
    - llvmdev =={{ version }}
    - clangdev =={{ version }}
    - libcxx =={{ version }}   # [osx]
    - libxml2
    - swig
    - libedit  # [linux]
  run:
    - libedit  # [linux]
    - llvmdev =={{ version }}
    - clangdev =={{ version }}
    - libcxx =={{ version }}   # [osx]
    - python

test:
  requires:
    - cmake >=3.4.3

  commands:
    - lldb --version

about:
  home: http://llvm.org/
  license: NCSA
  license_file: LICENSE.TXT
  summary: The LLVM Debugger

extra:
  recipe-maintainers:
    - inducer
    - isuruf
