{% set version = "14.0.1" %}
{% set sha256 = "c7deef63c5c4b3ee498a2c9d13d4b1913854957e51491de8434f3d9eefa9c77f" %}

package:
  name: lldb
  version: {{ version }}

source:
  url: https://github.com/llvm/llvm-project/releases/download/llvmorg-{{ version }}/lldb-{{ version }}.src.tar.xz
  sha256: {{ sha256 }}
  patches:
    # Fix Python and Mac support
    - python-mac.patch
build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.4.3
    - ninja
  host:
    - python
    - llvmdev =={{ version }}
    - clangdev =={{ version }}
    - llvm =={{ version }}
    - swig
    - ncurses  # [not win]
    - libedit  # [not win]
    - libxml2
    - xz
    - six
  run:
    - ncurses  # [not win]
    - libedit  # [not win]
    - python
    - six
  run_constrained:
    - llvmdev =={{ version }}
    - clangdev =={{ version }}

test:
  imports:
    - lldb
  commands:
    - lldb --version

about:
  home: http://llvm.org/
  license: NCSA
  license_file: LICENSE.TXT
  summary: The LLVM Debugger

extra:
  recipe-maintainers:
    - isuruf
