{% set version = "15.0.7" %}

package:
  name: lldb
  version: {{ version }}

source:
  url: https://github.com/llvm/llvm-project/releases/download/llvmorg-{{ version }}/llvm-project-{{ version }}.src.tar.xz
  sha256: 8b5fcb24b4128cf04df1b0b9410ce8b1a729cb3c544e6da885d234280dedeac6
  patches:
    # Fix Python and Mac support
    - patches/0001-Remove-linking-liblldb-to-libpython.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.4.3
    - ninja
  host:
    - python
    - llvmdev =={{ version }}
    - clangdev =={{ version }}
    - llvm =={{ version }}
    - swig
    - ncurses  # [not win]
    - libedit  # [not win]
    - libxml2
    - xz
    - zlib
    - zstd
    - six
  run:
    - ncurses  # [not win]
    - libedit  # [not win]
    - python
    - six
  run_constrained:
    - llvmdev =={{ version }}
    - clangdev =={{ version }}

test:
  imports:
    - lldb
  commands:
    - lldb --version

about:
  home: http://llvm.org/
  license: NCSA
  license_file: lldb/LICENSE.TXT
  summary: The LLVM Debugger

extra:
  recipe-maintainers:
    - isuruf
    - h-vetinari
