{% set version = "17.0.2" %}

package:
  name: lldb
  version: {{ version }}

source:
  url: https://github.com/llvm/llvm-project/releases/download/llvmorg-{{ version }}/llvm-project-{{ version }}.src.tar.xz
  sha256: 351562b14d42fcefcbf00cc1f327680a1062bbbf67a1e1ca6acb64c473b06394
  patches:
    # Fix Python and Mac support
    - patches/0001-Remove-linking-liblldb-to-libpython.patch  # [not win]
    # https://github.com/llvm/llvm-project/issues/59449
    # allows for compiling with older SDKs
    - patches/0001-Define-CPU_SUBTYPE_ARM64E-if-not-available.patch

build:
  number: 1
  # This needs clang-compiler-activation-feedstock build
  skip: true  # [osx and arm64]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - swig                                   # [build_platform != target_platform]
    - zlib                                   # [build_platform != target_platform]
    - llvmdev =={{ version }}                # [build_platform != target_platform]
    - clangdev =={{ version }}               # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - cmake >=3.4.3
    - ninja
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - python
    - llvmdev =={{ version }}
    - clangdev =={{ version }}
    - llvm =={{ version }}
    - libclang-cpp =={{ version }}
    - swig
    - ncurses  # [not win]
    - libedit  # [not win]
    - libxml2
    - xz
    - zlib
    - zstd
    - six
  run:
    - ncurses  # [not win]
    - libedit  # [not win]
    - python
    - six
  run_constrained:
    - llvmdev =={{ version }}
    - clangdev =={{ version }}

test:
  imports:
    - lldb
  commands:
    - lldb --version

about:
  home: http://llvm.org/
  license: NCSA
  license_file: lldb/LICENSE.TXT
  summary: The LLVM Debugger

extra:
  recipe-maintainers:
    - isuruf
    - h-vetinari
    - xhochy
