{% set version = "17.0.5" %}

package:
  name: lldb
  version: {{ version }}

source:
  url: https://github.com/llvm/llvm-project/releases/download/llvmorg-{{ version }}/llvm-project-{{ version }}.src.tar.xz
  sha256: 95d7eff82945cf05c16a1851d7b391fc2da726b87c1138125e3b6e4d300ab834
  patches:
    # Fix Python and Mac support
    - patches/0001-Remove-linking-liblldb-to-libpython.patch  # [not win]
    # https://github.com/llvm/llvm-project/issues/59449
    # allows for compiling with older SDKs
    - patches/0001-Define-CPU_SUBTYPE_ARM64E-if-not-available.patch
    # https://reviews.llvm.org/D156763
    - patches/6888de118707e6392b46073fc35738804f9f1d80.patch

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - swig                                   # [build_platform != target_platform]
    - zlib                                   # [build_platform != target_platform]
    - llvmdev =={{ version }}                # [build_platform != target_platform]
    - clangdev =={{ version }}               # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - cmake >=3.4.3
    - ninja
  host:
    - python
    - llvmdev =={{ version }}
    - clangdev =={{ version }}
    - llvm =={{ version }}
    - libclang-cpp =={{ version }}
    - swig
    - ncurses  # [not win]
    - libedit  # [not win]
    - libxml2
    - xz
    - zlib
    - zstd
    - six
  run:
    - ncurses  # [not win]
    - libedit  # [not win]
    - python
    - six
  run_constrained:
    - llvmdev =={{ version }}
    - clangdev =={{ version }}

test:
  imports:
    - lldb
  commands:
    - lldb --version

about:
  home: http://llvm.org/
  license: NCSA
  license_file: lldb/LICENSE.TXT
  summary: The LLVM Debugger

extra:
  recipe-maintainers:
    - isuruf
    - h-vetinari
    - xhochy
