{% set version = "10.0.0" %}
{% set sha256 = "dd1ffcb42ed033f5167089ec4c6ebe84fbca1db4a9eaebf5c614af09d89eb135" %}

package:
  name: lldb
  version: {{ version }}

source:
  url: https://github.com/llvm/llvm-project/releases/download/llvmorg-{{ version }}/lldb-{{ version }}.src.tar.xz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and py<35]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.4.3
    - ninja
  host:
    - python
    - llvmdev =={{ version }}
    - clangdev =={{ version }}
    - swig
    - libedit  # [linux]
    - ncurses
    - editline
    - libxml2
  run:
    - libedit  # [linux]
    - python
  run_constrained:
    - llvmdev =={{ version }}
    - clangdev =={{ version }}

test:
  commands:
    - lldb --version
    - python -c 'import lldb'

about:
  home: http://llvm.org/
  license: NCSA
  license_file: LICENSE.TXT
  summary: The LLVM Debugger

extra:
  recipe-maintainers:
    - inducer
    - isuruf
