{% set version = "6.0.1" %}
{% set sha256 = "6b8573841f2f7b60ffab9715c55dceff4f2a44e5a6d590ac189d20e8e7472714" %}

package:
  name: lldb
  version: {{ version }}

source:
  url: http://releases.llvm.org/{{ version }}/lldb-{{ version }}.src.tar.xz
  sha256: {{ sha256 }}
  patches:
    # Remove use of private header in LLDB
    # ref: https://reviews.llvm.org/D41824
    - D41824.patch

build:
  number: 0
  skip: true  # [win and py<35]
  features:
    - vc14    # [win and py>=35]

requirements:
  build:
    - toolchain
    - cmake >=3.4.3
    - ninja    # [win]
    - python
    - llvmdev =={{ version }}
    - clangdev =={{ version }}
    - libxml2 2.9.*
    - swig
    - libedit  # [linux]
    - vc 14    # [win]
    - libcxx   # [osx]
  run:
    - libedit  # [linux]
    - vc 14    # [win]
    - libcxx   # [osx]
    - llvmdev =={{ version }}
    - clangdev =={{ version }}
    - python

test:
  requires:
    - python {{ environ['PY_VER'] + '*' }}  # [win]
    - cmake >=3.4.3

  commands:
    - lldb --version

about:
  home: http://llvm.org/
  license: NCSA
  license_file: LICENSE.TXT
  summary: The LLVM Debugger

extra:
  recipe-maintainers:
    - inducer
    - isuruf
