context:
  version: "23.1.1"

package:
  name: lldb
  version: ${{ version }}

source:
  url: https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-${{ version|replace(".rc", "-rc") }}.tar.gz
  sha256: 851b3d701a4fbdd9f69536d4acda578469e810ca7056687d6556443f5fd39557
  patches:
    # Fix Python and Mac support
    - if: unix
      then: patches/0001-Remove-linking-liblldb-to-libpython.patch
    # https://github.com/llvm/llvm-project/issues/59449
    # allows for compiling with older SDKs
    - patches/0002-Define-CPU_SUBTYPE_ARM64E-if-not-available.patch
    - if: linux
      then:
        # https://github.com/llvm/llvm-project/issues/221704
        - patches/0003-lldb-also-build-libedit-integration-with-stable-ABI.patch
        - patches/0004-disable-python-libedit-bits.patch
        - patches/0005-allow-unresolved-symbols.patch

build:
  number: 0
  python:
    version_independent: ${{ is_abi3 }}
  skip: is_abi3 and not is_python_min

requirements:
  build:
    - ${{ stdlib("c") }}
    - ${{ compiler("cxx") }}
    - cmake >=3.4.3
    - ninja
    - if: build_platform != host_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - swig
        - zlib
        - llvmdev ==${{ version }}
        - clangdev ==${{ version }}
  host:
    - python
    # we're linking to `libpython3.{so,dylib}`
    - libpython
    - if: is_abi3
      then:  python-abi3
    - llvm ==${{ version }}
    - llvmdev ==${{ version }}
    - clangdev ==${{ version }}
    - libclang-cpp ==${{ version }}
    - swig
    - libxml2-devel
    - liblzma-devel
    - zlib
    - zstd
    - six
    - if: unix
      then:
        - libedit
        - ncurses
  run:
    - python
    # waiting for run-export, c.f. https://github.com/conda-forge/python-feedstock/pull/928 (+backports)
    - libpython
    - six
    - if: osx
      # we need to do this manually because clang_bootstrap has no run-export
      then: libcxx >=${{ version }}
  run_constraints:
    - llvmdev ==${{ version }}
    - clangdev ==${{ version }}

tests:
  - python:
      python_version:
        - ${{ python_min }}.*
        - "*"
      imports:
        - lldb
  - script:
      - lldb --version
      - lldb-argdumper --version
      - lldb-dap --version
      - lldb-instr --version
      # can't test without running server
      # - lldb-mcp --version
      # - lldb-server --version
      - yaml2macho-core --version
  - requirements:
      run:
        - abi3audit
    script:
      - if: unix
        then: abi3audit $SP_DIR/lldb/native/_lldb.abi3.so -s -v --assume-minimum-abi3 ${{ python_min }}
        else: abi3audit %SP_DIR%/lldb/native/_lldb.pyd -s -v --assume-minimum-abi3 ${{ python_min }}


about:
  homepage: http://llvm.org/
  repository: https://github.com/llvm/llvm-project
  license: Apache-2.0 WITH LLVM-exception
  license_file: lldb/LICENSE.TXT
  summary: The LLVM Debugger

extra:
  recipe-maintainers:
    - isuruf
    - h-vetinari
    - xhochy
