context:
  version: "22.1.8"

package:
  name: lldb
  version: ${{ version }}

source:
  url: https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-${{ version|replace(".rc", "-rc") }}.tar.gz
  sha256: ad18b70e287954c3d62bc7e0b86e7b7af2adf87bcfce21c15fe717f101d7aace
  patches:
    # Fix Python and Mac support
    - if: unix
      then: patches/0001-Remove-linking-liblldb-to-libpython.patch
    # https://github.com/llvm/llvm-project/issues/59449
    # allows for compiling with older SDKs
    - patches/0002-Define-CPU_SUBTYPE_ARM64E-if-not-available.patch
    # This is needed due to c-f's remove of pid_t in Python: https://github.com/conda-forge/python-feedstock/pull/767
    - if: win
      then:
        - patches/0003-Don-t-define-NO_PID_T-where-Python-is-patched.patch
        - patches/0004-fix-file-extension-on-windows.patch
    - if: linux
      then: patches/0005-lldb-also-build-libedit-integration-with-stable-ABI.patch

build:
  number: 1
  python:
    version_independent: ${{ is_abi3 }}
  skip: is_abi3 and not is_python_min

requirements:
  build:
    - ${{ stdlib("c") }}
    - ${{ compiler("cxx") }}
    - cmake >=3.4.3
    - ninja
    - if: build_platform != host_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - swig
        - zlib
        - llvmdev ==${{ version }}
        - clangdev ==${{ version }}
  host:
    - python
    - if: is_abi3
      then:  python-abi3
    - llvm ==${{ version }}
    - llvmdev ==${{ version }}
    - clangdev ==${{ version }}
    - libclang-cpp ==${{ version }}
    - swig
    - libxml2-devel
    - liblzma-devel
    - zlib
    - zstd
    - six
    - if: unix
      then:
        - libedit
        - ncurses
  run:
    - python
    - six
    - if: osx
      # we need to do this manually because clang_bootstrap has no run-export
      then: libcxx >=${{ version }}
  run_constraints:
    - llvmdev ==${{ version }}
    - clangdev ==${{ version }}

tests:
  - python:
      python_version:
        - ${{ python_min }}.*
        - "*"
      imports:
        - lldb
  - script:
      - lldb --version
  - requirements:
      run:
        - abi3audit
    script:
      - if: unix
        then: abi3audit $SP_DIR/lldb/native/_lldb.abi3.so -s -v --assume-minimum-abi3 ${{ python_min }}
        else: abi3audit %SP_DIR%/lldb/native/_lldb.pyd -s -v --assume-minimum-abi3 ${{ python_min }}


about:
  homepage: http://llvm.org/
  repository: https://github.com/llvm/llvm-project
  license: Apache-2.0 WITH LLVM-exception
  license_file: lldb/LICENSE.TXT
  summary: The LLVM Debugger

extra:
  recipe-maintainers:
    - isuruf
    - h-vetinari
    - xhochy
