travis:
  secure:
    BINSTAR_TOKEN: meU1u3tawilkjv7cHjlTrfEbgKpH8Hvofp9Zl57jyanmIuYLaL4PHWf3YOnpeq7ZwX6E1D+fJKblbSOGAq+sHWHe3M5qXe062YI97J5Rwn0Onmpjs2/f5scv56N4twv6DoabAHq7O+VTx+AhecIFwXLSjI1ziwQRNqSMKFzSwyv1rVb7jo2gVhhauq5Ec2Y4jJQLgYly8SAEHUi3GxNgH1Tcf2upUnsHhZ4Ffk4lcZDXcQY5tvuJ7sJ0+ubNMuJPDRYtU8CbEfO8GaBGUPzhSuNbBxfDUVxo3v/phqWjsDOpcqegDFMN4udAAHum/SEElVBpCyi5TrkrI/agamnBVnZmnTkTE4W1lglj28kTZdGwYZfEUKFxQ4M3EkJjan9sFAD/5xtxNPXiZ2NkYGu6i1LVqpmy3wi1b4raLm7f13y6N4MPMDb8aTkWgbU6bSuZtqFZieGjttQ+Gab+4jtjHvtn5hZZ4vAQGRDHkA3DljPnDfEQuVmvgce7MuOzj3nQndYrafGkqrLJjzeNZKUxV/26dumBlu6MGZ1V+/DSkaNVW2a/5fk/cMYKXUzPis0L6DqB3QqAti0899CMSJ7KK9kvAi+ShApw/QfOfpwFQ8FAWs6X2BguKwOoE/JI9xv1nAy0xghHr7a5dFGENfra/BbvjxV2F2DPYsXKkK2KMk8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
